openapi: 3.0.1
paths:
  '/collections/{collectionId}/versions':
    get:
      summary: returns a list of links for a versioned collection
      description: returns a list of links for a versioned collection
      tags:
        - Version Extension
      parameters:
        - $ref: '#/components/parameters/collectionId'
      responses:
        '200':
          description: A catalog JSON definition the returns list of links of a collection versions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/catalogDefinition'
  '/collections/{collectionId}/versions/{versionId}':
    get:
      summary: returns the requested version of a collection
      description: returns the requested version of a collection
      tags:
        - Version Extension
      parameters:
        - $ref: '#/components/parameters/collectionId'
        - $ref: '#/components/parameters/versionId'
      responses:
        '200':
          $ref: '#/components/responses/Collections'
  '/collections/{collectionId}/items/{featureId}/versions':
    get:
      summary: returns a list of links for a versioned item
      description: returns a list of links for a versioned item
      tags:
        - Version Extension
      parameters:
        - $ref: '#/components/parameters/collectionId'
        - $ref: '#/components/parameters/featureId'
      responses:
        '200':
          description: A catalog JSON definition the returns list of links of an item versions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/catalogDefinition'
  '/collections/{collectionId}/items/{featureId}/versions/{versionId}':
    get:
      summary: returns the requested version of an item
      description: returns the requested version of an item
      tags:
        - Version Extension
      parameters:
        - $ref: '#/components/parameters/collectionId'
        - $ref: '#/components/parameters/featureId'
        - $ref: '#/components/parameters/versionId'
      responses:
        '200':
          $ref: '#/components/responses/Collections'
components:
  schemas:
    catalogDefinition:
      type: object
      required:
        - stac_version
        - id
        - description
        - links
      properties:
        stac_version:
          $ref: '#/components/schemas/stac_version'
        stac_extensions:
          $ref: '#/components/schemas/stac_extensions'
        id:
          description: identifier of the catalog used, for example, in URIs
          type: string
        title:
          description: human readable title of the catalog
          type: string
        description:
          $ref: '#/components/schemas/description'
        links:
          type: array
          items:
            $ref: "#/components/schemas/link"
  parameters:
    versionId:
      name: versionId
      in: path
      description: local identifier of a version
      required: true
      schema:
        type: string